name: tradewise
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  action_slider: ^0.7.0
  cloud_firestore: ^4.14.0
  connectivity_plus: ^5.0.2
  device_preview: ^1.1.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  http: ^1.1.0
  intl: ^0.18.0
  provider: ^6.1.5
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter.ttf